on:
  pull_request:
    types: [opened, edited]
  workflow_dispatch:

concurrency:
  group: ${{ github.event_name }}-${{ github.ref }}

jobs:
  pr-job-one:
    runs-on: ubuntu-latest
    steps:
      - run: |
          for i in {1..30}; do
            echo "Number $i"
            sleep 1
          done
          echo "Loop finished!"
          
